version: '3.8'

services:
  fastapi:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/model # Update this if needed
    volumes:
      - ./model:/app/model  # Mount the model directory
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - monitoring
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge
